[project]
name = "zoos"
version = "1.0.0"
description = "Zoos i Danmark"
dependencies = [
    "flask (==3.1.1)",
    "pandas (==2.2.3)",
    "requests (==2.31.0)"
]

[tool.setuptools]
py-modules = []
